import Devcon from '../../../assets/img/devcon.png';
import Weather from '../../../assets/img/weather.png';

export const ProjectsList = [
  {
    name: 'Developer Connector',
    shortDescription: 'Social network that helps employers to find developers',
    description: 'Social network that helps employers to find developers',
    github: 'https://github.com/ViktorSheverdin/devNetwork',
    demoURL: 'https://protected-river-13776.herokuapp.com/',
    img: Devcon,
    technologies: ['React', 'Node.js', 'Python'],
  },
  {
    name: 'Weather forecast',
    shortDescription: 'Social network that helps employers to find developers',
    description: 'Classical weather forecast project',
    github: 'https://github.com/ViktorSheverdin/weather_application',
    demoURL: 'https://yetanotherweatherapp.herokuapp.com/',
    img: Devcon,
    technologies: ['React'],
  },
  {
    name: 'Developer Connector',
    shortDescription: 'Social network that helps employers to find developers',
    description: 'Social network that helps employers to find developers',
    github: 'https://github.com/ViktorSheverdin/devNetwork',
    demoURL: 'https://protected-river-13776.herokuapp.com/',
    img: Weather,
    technologies: ['React'],
  },
  {
    name: 'Weather forecast',
    shortDescription: 'Social network that helps employers to find developers',
    description: 'Classical weather forecast project',
    github: 'https://github.com/ViktorSheverdin/weather_application',
    demoURL: 'https://yetanotherweatherapp.herokuapp.com/',
    img: Devcon,
    technologies: ['JavaScript'],
  },
  {
    name: 'Developer Connector',
    shortDescription: 'Social network that helps employers to find developers',
    description: 'Social network that helps employers to find developers',
    github: 'https://github.com/ViktorSheverdin/devNetwork',
    demoURL: 'https://protected-river-13776.herokuapp.com/',
    img: Weather,
    technologies: ['Node.js'],
  },
  {
    name: 'Weather forecast',
    shortDescription: 'Social network that helps employers to find developers',
    description: 'Classical weather forecast project',
    github: 'https://github.com/ViktorSheverdin/weather_application',
    demoURL: 'https://yetanotherweatherapp.herokuapp.com/',
    img: Devcon,
    technologies: ['Python'],
  },
  {
    name: 'Weather forecast',
    shortDescription: 'Social network that helps employers to find developers',
    description: 'Classical weather forecast project',
    github: 'https://github.com/ViktorSheverdin/weather_application',
    demoURL: 'https://yetanotherweatherapp.herokuapp.com/',
    img: Devcon,
    technologies: ['JS'],
  },
];
