export const ProjectsList = [
  {
    name: 'Developer Connector',
    description: 'Social network that helps employers to find developers',
    github: 'https://github.com/ViktorSheverdin/devNetwork',
    demoURL: 'https://protected-river-13776.herokuapp.com/',
    imgURL: '../../../assets/img/devcon.png',
    technology: ['React', 'Node.js'],
  },
  {
    name: 'Weather forecast',
    description: 'Classical weather forecast project',
    github: 'https://github.com/ViktorSheverdin/weather_application',
    demoURL: 'https://yetanotherweatherapp.herokuapp.com/',
    imgURL: '../../../assets/img/weather.png',
    technology: ['JavaScript'],
  },
  {
    name: 'Developer Connector',
    description: 'Social network that helps employers to find developers',
    github: 'https://github.com/ViktorSheverdin/devNetwork',
    demoURL: 'https://protected-river-13776.herokuapp.com/',
    imgURL: '../../../assets/img/devcon.png',
    technology: ['React'],
  },
  {
    name: 'Weather forecast',
    description: 'Classical weather forecast project',
    github: 'https://github.com/ViktorSheverdin/weather_application',
    demoURL: 'https://yetanotherweatherapp.herokuapp.com/',
    imgURL: '../../../assets/img/weather.png',
    technology: ['JavaScript'],
  },
  {
    name: 'Developer Connector',
    description: 'Social network that helps employers to find developers',
    github: 'https://github.com/ViktorSheverdin/devNetwork',
    demoURL: 'https://protected-river-13776.herokuapp.com/',
    imgURL: '../../../assets/img/devcon.png',
    technology: ['Node.js'],
  },
  {
    name: 'Weather forecast',
    description: 'Classical weather forecast project',
    github: 'https://github.com/ViktorSheverdin/weather_application',
    demoURL: 'https://yetanotherweatherapp.herokuapp.com/',
    imgURL: '../../../assets/img/devcon.png',
    technology: ['Python'],
  },
];
